[package]
name = "enum-map"
version = "0.1.0"
edition = "2021"

[dependencies]
enummap-macros = { path = "../enummap-macros" }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "enummap"
harness = false
