[package]
name = "enum-collections"
version = "0.1.0"
edition = "2021"

description = "Collections data structures optimized for Enum, initializable at runtime. EnumMap."
authors = ["Pavel Pscheidl <pavel2@pscheidl.cz>"]
readme = "../README.md"
repository = "https://github.com/Pscheidl/enum-map"
license = "Apache-2.0"
keywords = ["collections", "hashmap", "enum"]
categories = ["data-structures", "no-std"]
documentation = "https://docs.rs/enum-collections"

[dependencies]
enum-collections-macros = { version = "0.1.0", path = "../enum-collections-macros" }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "enummap"
harness = false
