[package]
name = "enum-collections-macros"
version = "0.1.0"
edition = "2021"

description = "Macros to make EnumCollections easy to use"
authors = ["Pavel Pscheidl <pavel2@pscheidl.cz>"]
readme = "../README.md"
repository = "https://github.com/Pscheidl/enum-map"
license = "Apache-2.0"
keywords = ["collections", "hashmap", "enum"]
categories = ["data-structures", "no-std"]


[lib]
proc-macro = true

[dependencies]
syn = "1.0"
